#!/bin/sh

#convert julia.pgm julia0000.png

for i in imgs/difusion/julia_????.pgm
do
convert $i imgs/`basename $i .pgm`.png
done
ffmpeg -framerate 5 -i imgs/difusion/julia_%04d.png -s:v 640x480 -c:v libx264 \
-profile:v high -crf 20 -pix_fmt yuv420p julia.mp4

