#!/bin/sh

for i in imgs/normal/julia_????.pgm
do
    convert $i imgs/normal/`basename $i .pgm`.png
    rm $i
done

for i in imgs/difusion/julia_????.pgm
do
    convert $i imgs/difusion/`basename $i .pgm`.png
    rm $i
done

ffmpeg -framerate 5 -i imgs/normal/julia_%04d.png -s:v 640x480 -c:v libx264 \
-profile:v high -crf 20 -pix_fmt yuv420p julia.mp4

ffmpeg -framerate 5 -i imgs/difusion/julia_%04d.png -s:v 640x480 -c:v libx264 \
-profile:v high -crf 20 -pix_fmt yuv420p julia_difusion.mp4

